//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scholarship
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScholarshipEntities : DbContext
    {
        public ScholarshipEntities()
            : base("name=ScholarshipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_login> tbl_login { get; set; }
        public virtual DbSet<tblException> tblExceptions { get; set; }
        public virtual DbSet<tblStudentDetail> tblStudentDetails { get; set; }
        public virtual DbSet<tblScholarship> tblScholarships { get; set; }
    }
}
