//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scholarship
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScholarship
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public int Amount { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public Nullable<int> MinStd { get; set; }
        public Nullable<int> MaxStd { get; set; }
    }
}
