//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scholarship
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentResult
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int Standard { get; set; }
        public string Time { get; set; }
        public System.DateTime CreataionDate { get; set; }
        public string result { get; set; }
    }
}
