//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scholarship
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ParentName { get; set; }
        public string SurName { get; set; }
        public string ContactNumber { get; set; }
        public string EmailId { get; set; }
        public string Address { get; set; }
        public string AlternetContactNumber { get; set; }
        public string AlternateEmailId { get; set; }
        public int STD { get; set; }
        public string SubjectInterested { get; set; }
        public string SchoolName { get; set; }
        public string SchoolAddress { get; set; }
        public string SchoolContactNumber { get; set; }
        public string PrincipalName { get; set; }
        public string SchoolEmailId { get; set; }
        public string Goal_In_Life { get; set; }
        public bool Apply_Scholarship { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}
