//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scholarship
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStdPaymentDetail
    {
        public int Id { get; set; }
        public int Stdid { get; set; }
        public decimal Amount { get; set; }
        public string ScholarshipId { get; set; }
        public string TransacrtionId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> ReceiptNumber { get; set; }
    }
}
